name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    # リポジトリをチェックアウトする
    - name: Checkout repository
      uses: actions/checkout@v6

    # Node.js のバージョンをセットアップする
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '18'
        cache: npm

    # パッケージのインストール
    - name: Install dependencies
      run: npm ci

    # ビルド
    - name: Run tests using Makefile
      run: make check
